<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Armada;
use App\Models\ArmadaType;
use Faker\Factory as Faker;
use DB;

class ArmadaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $armadas = array(
            array('id' => '1','salespoint_id' => '162','armada_type_id' => '8','plate' => 'DD1691YJ','status' => '1','booked_by' => 'MUH SAIL','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '2','salespoint_id' => '162','armada_type_id' => '8','plate' => 'KT1346LW','status' => '1','booked_by' => 'ABDUL HARIS','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '3','salespoint_id' => '162','armada_type_id' => '8','plate' => 'L1180GK','status' => '1','booked_by' => 'ANDRI PRASETYO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '4','salespoint_id' => '162','armada_type_id' => '8','plate' => 'DA1286PM','status' => '1','booked_by' => 'ROMY ARIS WIJAYA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '5','salespoint_id' => '162','armada_type_id' => '8','plate' => 'KT1766ZH','status' => '1','booked_by' => 'ACHMAD RONALDI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '6','salespoint_id' => '162','armada_type_id' => '8','plate' => 'DA1273PX','status' => '1','booked_by' => 'SYAIFUL','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '7','salespoint_id' => '8','armada_type_id' => '8','plate' => 'L1711AH','status' => '1','booked_by' => 'DENI IRAWAN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '8','salespoint_id' => '274','armada_type_id' => '8','plate' => 'DA1975WL','status' => '1','booked_by' => 'MUHAMMAD SYAFII','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '9','salespoint_id' => '162','armada_type_id' => '8','plate' => 'L1690HX','status' => '1','booked_by' => 'SUNOKO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '10','salespoint_id' => '162','armada_type_id' => '10','plate' => 'DH1198AY','status' => '1','booked_by' => 'YOHANES MULYOKO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '11','salespoint_id' => '17','armada_type_id' => '10','plate' => 'DB1410LQ','status' => '1','booked_by' => 'ANTHONIUS STEFEN AWUY','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '12','salespoint_id' => '275','armada_type_id' => '10','plate' => 'DD1747QP','status' => '1','booked_by' => 'ALBAR SIMU FAALU','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '13','salespoint_id' => '210','armada_type_id' => '10','plate' => 'KB1685MD','status' => '1','booked_by' => 'ANTONIUS','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '14','salespoint_id' => '162','armada_type_id' => '10','plate' => 'KT1781KO','status' => '1','booked_by' => 'DODO TRIYO PRAMONO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '15','salespoint_id' => '275','armada_type_id' => '8','plate' => 'DD1549UM','status' => '1','booked_by' => 'SUARDI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '16','salespoint_id' => '8','armada_type_id' => '8','plate' => 'DK1710OG','status' => '1','booked_by' => 'I WAYAN ASTANA PUTRA WIDIARSA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '17','salespoint_id' => '8','armada_type_id' => '8','plate' => 'DK1711OG','status' => '1','booked_by' => 'I GEDE PUTRA ARIANA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '18','salespoint_id' => '275','armada_type_id' => '8','plate' => 'L1708AH','status' => '1','booked_by' => 'HENGGI PRIONGGO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '19','salespoint_id' => '17','armada_type_id' => '8','plate' => 'DB1510LU','status' => '1','booked_by' => 'RAMLI SALEH','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '20','salespoint_id' => '19','armada_type_id' => '8','plate' => 'L1820YF','status' => '1','booked_by' => 'BUDI HARTONO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '21','salespoint_id' => '8','armada_type_id' => '8','plate' => 'L1535LQ','status' => '1','booked_by' => 'ARDYAN ABDI NUGROHO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '22','salespoint_id' => '8','armada_type_id' => '8','plate' => 'L1606QW','status' => '1','booked_by' => 'SOFYAN HADI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '23','salespoint_id' => '8','armada_type_id' => '8','plate' => 'L1257I','status' => '1','booked_by' => 'IBNU DAROJAT','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '24','salespoint_id' => '8','armada_type_id' => '8','plate' => 'L1174GK','status' => '1','booked_by' => 'JONI PURWANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '25','salespoint_id' => '162','armada_type_id' => '8','plate' => 'DT1379YE','status' => '1','booked_by' => 'ALEX FERDINAND ONIBALA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '26','salespoint_id' => '162','armada_type_id' => '8','plate' => 'DH1750HJ','status' => '1','booked_by' => 'JOHANIS LABU IPI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '27','salespoint_id' => '162','armada_type_id' => '8','plate' => 'W1157NJ','status' => '1','booked_by' => 'AFRI PRASETYO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '28','salespoint_id' => '17','armada_type_id' => '8','plate' => 'L1932IO','status' => '1','booked_by' => 'JENLY TORIQ SAEFUDIN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '29','salespoint_id' => '17','armada_type_id' => '8','plate' => 'B2017BIF','status' => '1','booked_by' => 'YENY LUSIAWATI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '30','salespoint_id' => '162','armada_type_id' => '8','plate' => 'DD1736YV','status' => '1','booked_by' => 'SYARIFUDDIN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '31','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'DD1735YV','status' => '1','booked_by' => 'ANNA CHRYSANTIA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '32','salespoint_id' => '162','armada_type_id' => '8','plate' => 'L1522BG','status' => '1','booked_by' => 'CHAHYA PRATAMA PUTRA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '33','salespoint_id' => '162','armada_type_id' => '8','plate' => 'L1375IO','status' => '1','booked_by' => 'BUDI SANTOSO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '34','salespoint_id' => '8','armada_type_id' => '8','plate' => 'B2261SYN','status' => '1','booked_by' => 'DWI HANDAYANI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '35','salespoint_id' => '8','armada_type_id' => '8','plate' => 'B2419SZT','status' => '1','booked_by' => 'SURYO DWI HANDOKO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '36','salespoint_id' => '165','armada_type_id' => '8','plate' => 'DB1076LJ','status' => '1','booked_by' => 'ERWIN EVERT','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '37','salespoint_id' => '19','armada_type_id' => '8','plate' => 'DR1153BE','status' => '1','booked_by' => 'LALU BURMAN ALU','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '38','salespoint_id' => '19','armada_type_id' => '8','plate' => 'DR1686BM','status' => '1','booked_by' => 'PAESAL AMIR','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '39','salespoint_id' => '162','armada_type_id' => '8','plate' => 'L1457GY','status' => '1','booked_by' => 'NOR ACHYANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '40','salespoint_id' => '8','armada_type_id' => '8','plate' => 'B2667SZY','status' => '1','booked_by' => 'NENO ROMAN ISWAHYUDI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '41','salespoint_id' => '162','armada_type_id' => '8','plate' => 'L1451GY','status' => '1','booked_by' => 'MUHAMMAD HAMDI TAUFIQURROHIM','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '42','salespoint_id' => '165','armada_type_id' => '8','plate' => 'L1492GC','status' => '1','booked_by' => 'M KURNIA ARIP BOWO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '43','salespoint_id' => '275','armada_type_id' => '8','plate' => 'DD1886VL','status' => '1','booked_by' => 'AZRULDDIN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '44','salespoint_id' => '19','armada_type_id' => '8','plate' => 'DN1017NQ','status' => '1','booked_by' => 'ALBERT PAREWANG','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '45','salespoint_id' => '162','armada_type_id' => '8','plate' => 'L1032IH','status' => '1','booked_by' => 'SYAMSUL AFANDI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '46','salespoint_id' => '19','armada_type_id' => '8','plate' => 'DD1698YJ','status' => '1','booked_by' => 'SUPRIANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '47','salespoint_id' => '162','armada_type_id' => '8','plate' => 'B2934BIE','status' => '1','booked_by' => 'YUDHISTIRA  IRIANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '48','salespoint_id' => '171','armada_type_id' => '8','plate' => 'L1691ZZ','status' => '1','booked_by' => 'TEGUH CAHYONO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '49','salespoint_id' => '210','armada_type_id' => '8','plate' => 'KB1359MF','status' => '1','booked_by' => 'ADI SUSANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '50','salespoint_id' => '19','armada_type_id' => '8','plate' => 'KB1510MD','status' => '1','booked_by' => 'ADI YULIANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '51','salespoint_id' => '171','armada_type_id' => '8','plate' => 'B2080SYA','status' => '1','booked_by' => 'ABDUL HAMID','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '52','salespoint_id' => '8','armada_type_id' => '8','plate' => 'B2617SIK','status' => '1','booked_by' => 'SARIFFUDIN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '53','salespoint_id' => '162','armada_type_id' => '8','plate' => 'KT1784AQ','status' => '1','booked_by' => 'JIMMY PUTRA EKA NURDIN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '54','salespoint_id' => '275','armada_type_id' => '8','plate' => 'DA1301BY','status' => '1','booked_by' => 'BENNY VOKTO KURNIAWAN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '55','salespoint_id' => '19','armada_type_id' => '8','plate' => 'DR1528BE','status' => '1','booked_by' => 'RUSNAN EFENDI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '56','salespoint_id' => '19','armada_type_id' => '8','plate' => 'DR1437BM','status' => '1','booked_by' => 'MUHAMMAD ARONI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '57','salespoint_id' => '275','armada_type_id' => '8','plate' => 'L1321HG','status' => '1','booked_by' => 'NURHADI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '58','salespoint_id' => '275','armada_type_id' => '8','plate' => 'L1374IO','status' => '1','booked_by' => 'PRADIPTA RAHARDIAN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '59','salespoint_id' => '17','armada_type_id' => '8','plate' => 'DK1383QL','status' => '1','booked_by' => 'SAYUDI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '60','salespoint_id' => '165','armada_type_id' => '8','plate' => 'KB1451MF','status' => '0','booked_by' => NULL,'deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '61','salespoint_id' => '162','armada_type_id' => '8','plate' => 'L1727AH','status' => '1','booked_by' => 'SANDRAWAN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '62','salespoint_id' => '162','armada_type_id' => '9','plate' => 'B2532UKX','status' => '1','booked_by' => 'ALDERIA KURNIA WARDHANI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '63','salespoint_id' => '8','armada_type_id' => '10','plate' => 'L1043IH','status' => '1','booked_by' => 'ARMANSYAH','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '64','salespoint_id' => '19','armada_type_id' => '10','plate' => 'DK1011OO','status' => '1','booked_by' => 'ABRAHAM ANRYANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '65','salespoint_id' => '19','armada_type_id' => '9','plate' => 'KB1294ME','status' => '1','booked_by' => 'ANGELIA SISKA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '66','salespoint_id' => '162','armada_type_id' => '9','plate' => 'KT1572AB','status' => '1','booked_by' => 'ANTONIUS AGUNG','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '67','salespoint_id' => '275','armada_type_id' => '9','plate' => 'B2475BKF','status' => '1','booked_by' => 'EUNIKE INTAR DARMADJO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '68','salespoint_id' => '166','armada_type_id' => '8','plate' => 'L1137IG','status' => '1','booked_by' => 'SHOLIHUDDIN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '69','salespoint_id' => '17','armada_type_id' => '8','plate' => 'DD1942RC','status' => '1','booked_by' => 'HENDRY SYAM','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '70','salespoint_id' => '8','armada_type_id' => '8','plate' => 'L1713K','status' => '1','booked_by' => 'HAFIDZ BAHTIAR','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '71','salespoint_id' => '163','armada_type_id' => '8','plate' => 'B2580BZL','status' => '1','booked_by' => 'YOSARTHA GALUH WIJAYA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '72','salespoint_id' => '17','armada_type_id' => '8','plate' => 'L1892II','status' => '1','booked_by' => 'EKO HARI CAHYONO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '73','salespoint_id' => '19','armada_type_id' => '8','plate' => 'L1887WR','status' => '1','booked_by' => 'JUDO RAHARDJO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '74','salespoint_id' => '162','armada_type_id' => '8','plate' => 'DD1734YV','status' => '1','booked_by' => 'FREDY TODING','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '75','salespoint_id' => '8','armada_type_id' => '10','plate' => 'B2645SZT','status' => '1','booked_by' => 'ANTHONY DWI RAHARJO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '76','salespoint_id' => NULL,'armada_type_id' => '10','plate' => 'B2194SIU','status' => '1','booked_by' => 'RAMLAN SALEH','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '77','salespoint_id' => NULL,'armada_type_id' => '10','plate' => 'BM1637VI','status' => '1','booked_by' => 'JOHNSON','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '78','salespoint_id' => '17','armada_type_id' => '10','plate' => 'B2106SZW','status' => '1','booked_by' => 'IVAN HARTONO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '79','salespoint_id' => NULL,'armada_type_id' => '10','plate' => 'D1891AGU','status' => '1','booked_by' => 'TARMIDI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '80','salespoint_id' => NULL,'armada_type_id' => '10','plate' => 'B2653SYD','status' => '1','booked_by' => 'TONI KURNIAWAN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '81','salespoint_id' => '8','armada_type_id' => '10','plate' => 'B2338SZS','status' => '1','booked_by' => 'MUHAMMAD NOVRI WANJAYA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '82','salespoint_id' => '8','armada_type_id' => '10','plate' => 'BG1320O','status' => '1','booked_by' => 'WILLIAM','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '83','salespoint_id' => NULL,'armada_type_id' => '10','plate' => 'B2102SZU','status' => '1','booked_by' => 'MUHAMMAD RIDLO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '84','salespoint_id' => NULL,'armada_type_id' => '14','plate' => 'B2870UFE','status' => '1','booked_by' => 'GA HO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '85','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'KT1663AB','status' => '1','booked_by' => 'YOHANES','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '86','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'BK1430AAQ','status' => '1','booked_by' => 'MARYUN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '87','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'PA1464R','status' => '1','booked_by' => 'SYAMSUDDIN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '88','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'BK1903AAQ','status' => '1','booked_by' => 'HUSNI THAMRIN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '89','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'DB1390LX','status' => '1','booked_by' => 'FRANGKY VALENTINO A','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '90','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'BK1182AAW','status' => '1','booked_by' => 'M ANDRY SAPUTRA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '91','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'BK1429AAQ','status' => '1','booked_by' => 'ZULFIKAR','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '92','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'DD1687QE','status' => '1','booked_by' => 'ADHIKA AGRESTA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '93','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'BK1561HX','status' => '1','booked_by' => 'WAHYUDI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '94','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'BK1099AAG','status' => '1','booked_by' => 'MUHAMMAD ZULFIQQI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '95','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'BM1310QX','status' => '1','booked_by' => 'AKMAL SYAFII RITONGA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '96','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'BM1986TE','status' => '1','booked_by' => 'WIDIANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '97','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'BK1183AAW','status' => '1','booked_by' => 'SUWANTO T','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '98','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'BK1930KU','status' => '1','booked_by' => 'JOKO BAIDARUS','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '99','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'B2836SZZ','status' => '1','booked_by' => 'HENDRA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '100','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'KT1728AY','status' => '1','booked_by' => 'SUWARDI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '101','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'DB1559LU','status' => '1','booked_by' => 'IMAGINE GALERY W','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '102','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'DN1075NR','status' => '1','booked_by' => 'VACANT','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '103','salespoint_id' => NULL,'armada_type_id' => '10','plate' => 'B2603SIT','status' => '1','booked_by' => 'WILSON CLEMENS','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '104','salespoint_id' => '162','armada_type_id' => '10','plate' => 'B2951SZT','status' => '1','booked_by' => 'LOUIS ANTHONIUS JULIANTO PRAJA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '105','salespoint_id' => '8','armada_type_id' => '10','plate' => 'B2944SZT','status' => '1','booked_by' => 'KELVIN YOHANES','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '106','salespoint_id' => NULL,'armada_type_id' => '10','plate' => 'B2916SZT','status' => '1','booked_by' => 'SUMARNI ','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '107','salespoint_id' => NULL,'armada_type_id' => '11','plate' => 'B2588SYC','status' => '1','booked_by' => 'AHMAD WIRA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '108','salespoint_id' => '8','armada_type_id' => '10','plate' => 'B2906SYR','status' => '1','booked_by' => 'SUPARDI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '109','salespoint_id' => NULL,'armada_type_id' => '10','plate' => 'B2856SZY','status' => '1','booked_by' => 'GABRIEL CHYNTIA MICHELA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '110','salespoint_id' => NULL,'armada_type_id' => '11','plate' => 'D1105AGL','status' => '1','booked_by' => 'DINA NURUL CHOTIMAH','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '111','salespoint_id' => '8','armada_type_id' => '10','plate' => 'B2982SYI','status' => '1','booked_by' => 'TANDY FERDIAN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '112','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'D1786AHB','status' => '1','booked_by' => 'ANDRI JAYAKUSUMA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '113','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'D1495AHB','status' => '1','booked_by' => 'UUS SUTANDI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '114','salespoint_id' => '275','armada_type_id' => '8','plate' => 'D1481AIO','status' => '1','booked_by' => 'ASEP MUHYIDIN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '115','salespoint_id' => '275','armada_type_id' => '8','plate' => 'B2007SZZ','status' => '1','booked_by' => 'SANDI SUPRIATNA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '116','salespoint_id' => '162','armada_type_id' => '8','plate' => 'BH1531NI','status' => '1','booked_by' => 'DEDI HARYANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '117','salespoint_id' => '17','armada_type_id' => '8','plate' => 'D1785AHB','status' => '1','booked_by' => 'WANDI KUSWANDI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '118','salespoint_id' => '8','armada_type_id' => '8','plate' => 'D1216AGS','status' => '1','booked_by' => 'TATANG SUTISNA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '119','salespoint_id' => '8','armada_type_id' => '8','plate' => 'D1783AHB','status' => '1','booked_by' => 'RACHMAT ZUFRIJAL','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '120','salespoint_id' => '8','armada_type_id' => '8','plate' => 'BD1339CV','status' => '1','booked_by' => 'BAIJONI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '121','salespoint_id' => '8','armada_type_id' => '8','plate' => 'BD1650CA','status' => '1','booked_by' => 'JIMMY CHALTER','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '122','salespoint_id' => '162','armada_type_id' => '8','plate' => 'BK1031CW','status' => '1','booked_by' => 'WINARNO RAHMAD SINAMBELA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '123','salespoint_id' => '8','armada_type_id' => '8','plate' => 'B1418NZJ','status' => '1','booked_by' => 'IRWANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '124','salespoint_id' => '19','armada_type_id' => '8','plate' => 'BA1737QB','status' => '1','booked_by' => 'SONNIE ZULKARNAIN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '125','salespoint_id' => '162','armada_type_id' => '8','plate' => 'B2225SYC','status' => '1','booked_by' => 'WILLY HENDRA HIDAYAT','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '126','salespoint_id' => '8','armada_type_id' => '8','plate' => 'B2448SIK','status' => '1','booked_by' => 'ANDE HERMAWAN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '127','salespoint_id' => '8','armada_type_id' => '8','plate' => 'B2773SYA','status' => '1','booked_by' => 'SUPARDI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '128','salespoint_id' => '162','armada_type_id' => '8','plate' => 'B2325UFI','status' => '1','booked_by' => 'SUPRI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '129','salespoint_id' => '162','armada_type_id' => '8','plate' => 'D1606AGS','status' => '1','booked_by' => 'IWAN RAMDANI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '130','salespoint_id' => '162','armada_type_id' => '8','plate' => 'D1775AHB','status' => '1','booked_by' => 'RIFAN HIDAYANA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '131','salespoint_id' => '162','armada_type_id' => '8','plate' => 'D1812AHZ','status' => '1','booked_by' => 'AGUNG SEDAYU YUSWANDI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '132','salespoint_id' => '275','armada_type_id' => '8','plate' => 'D1768AHB','status' => '1','booked_by' => 'FAHRUL ROMLI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '133','salespoint_id' => '162','armada_type_id' => '8','plate' => 'D1750AHB','status' => '1','booked_by' => 'ALIYANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '134','salespoint_id' => '17','armada_type_id' => '8','plate' => 'B2355UFF','status' => '1','booked_by' => 'FADLY SUKMA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '135','salespoint_id' => '162','armada_type_id' => '8','plate' => 'D1855AHH','status' => '1','booked_by' => 'FAJAR RAMDANI KUSUMA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '136','salespoint_id' => '162','armada_type_id' => '8','plate' => 'B2131SZX','status' => '1','booked_by' => 'BUHORI MUSLIM','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '137','salespoint_id' => '162','armada_type_id' => '8','plate' => 'B2514UKC','status' => '1','booked_by' => 'WAHYUDIN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '138','salespoint_id' => '17','armada_type_id' => '8','plate' => 'D1789AHB','status' => '1','booked_by' => 'DODY HERIYANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '139','salespoint_id' => '17','armada_type_id' => '8','plate' => 'B2084BYJ','status' => '1','booked_by' => 'YUDA PUTRA PRATAMA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '140','salespoint_id' => '19','armada_type_id' => '8','plate' => 'D1655AHB','status' => '1','booked_by' => 'ALEX PURWANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '141','salespoint_id' => '17','armada_type_id' => '8','plate' => 'B2652UFZ','status' => '1','booked_by' => 'AGUNG LESMANA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '142','salespoint_id' => '17','armada_type_id' => '8','plate' => 'D1664AHF','status' => '1','booked_by' => 'CECEP SAMUDRA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '143','salespoint_id' => '162','armada_type_id' => '8','plate' => 'D1481AHB','status' => '1','booked_by' => 'IZMA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '144','salespoint_id' => '8','armada_type_id' => '8','plate' => 'B2272SYN','status' => '1','booked_by' => 'MOCH. SALIPI SALASAH','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '145','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'AB1370RY','status' => '1','booked_by' => 'BUDI HERMANSYAH','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '146','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'B2818BIF','status' => '1','booked_by' => 'ASEP SOLEH','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '147','salespoint_id' => '162','armada_type_id' => '8','plate' => 'BA1316OT','status' => '1','booked_by' => 'SARI WAHYUNI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '148','salespoint_id' => '19','armada_type_id' => '8','plate' => 'B2761UKV','status' => '1','booked_by' => 'LUARMAN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '149','salespoint_id' => '8','armada_type_id' => '8','plate' => 'BM1764OZ','status' => '1','booked_by' => 'HEFRIANDI BUTAR BUTAR','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '150','salespoint_id' => '19','armada_type_id' => '8','plate' => 'BM1021OS','status' => '1','booked_by' => 'PUJI SUGIONO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '151','salespoint_id' => '17','armada_type_id' => '8','plate' => 'DK1695FAD','status' => '1','booked_by' => 'YUSRIN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '152','salespoint_id' => '274','armada_type_id' => '8','plate' => 'DR1405XG','status' => '1','booked_by' => 'FUAD','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '153','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'BM1831VH','status' => '1','booked_by' => 'FAISAL IHUT TUA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '154','salespoint_id' => '275','armada_type_id' => '8','plate' => 'BA1117OL','status' => '1','booked_by' => 'SAMSUL BAHARI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '155','salespoint_id' => '275','armada_type_id' => '8','plate' => 'BK1952KU','status' => '1','booked_by' => 'TENGKU RICKY EFFENDI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '156','salespoint_id' => '276','armada_type_id' => '8','plate' => 'DK1319OI','status' => '1','booked_by' => 'FREDERIKUS A.','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '157','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'BM1785QQ','status' => '1','booked_by' => 'HENDRO PURNOMO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '158','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'B2231SYC','status' => '1','booked_by' => 'ARIYANDI WARDANA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '159','salespoint_id' => '162','armada_type_id' => '8','plate' => 'DH1558HG','status' => '1','booked_by' => 'ALFONS NDABUNG','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '160','salespoint_id' => '162','armada_type_id' => '8','plate' => 'BA1130BC','status' => '1','booked_by' => 'ROBY SUGARA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '161','salespoint_id' => '17','armada_type_id' => '8','plate' => 'DR1671BG','status' => '1','booked_by' => 'DENI JP','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '162','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'BM1876OT','status' => '1','booked_by' => 'BENTAR DIPRI SAPUTRA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '163','salespoint_id' => '8','armada_type_id' => '8','plate' => 'BM1763OZ','status' => '1','booked_by' => 'BENNY FRANOTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '164','salespoint_id' => '276','armada_type_id' => '8','plate' => 'BK1724SX','status' => '1','booked_by' => 'NIRWANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '165','salespoint_id' => '162','armada_type_id' => '8','plate' => 'BM1442AK','status' => '1','booked_by' => 'HERYANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '166','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'B2054SYC','status' => '1','booked_by' => 'ADITYA WARMAN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '167','salespoint_id' => '275','armada_type_id' => '8','plate' => 'DR1636XG','status' => '1','booked_by' => 'JEKSEN VICTOR C','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '168','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'B2341UFI','status' => '1','booked_by' => 'MADIN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '169','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'B2759UKJ','status' => '1','booked_by' => 'MOHAMAD RIDWAN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '170','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'D1748AHB','status' => '1','booked_by' => 'DENDEN SOMANTRI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '171','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'D1858AHH','status' => '1','booked_by' => 'HELMI NUGROHO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '172','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'B2478SZT','status' => '1','booked_by' => 'JAINUDIN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '173','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'B2339UFI','status' => '1','booked_by' => 'YUSMAN GUNAWAN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '174','salespoint_id' => '8','armada_type_id' => '8','plate' => 'BH1478NG','status' => '1','booked_by' => 'ANDRY FEBRIANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '175','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'B2268SYN','status' => '1','booked_by' => 'ERICK ERLANGGA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '176','salespoint_id' => '8','armada_type_id' => '8','plate' => 'B2006BYK','status' => '1','booked_by' => 'NURUL ANWAR','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '177','salespoint_id' => '162','armada_type_id' => '8','plate' => 'BK1129AAQ','status' => '1','booked_by' => 'AGUS SYAHPUTRA ASHARI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '178','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'B2437UKC','status' => '1','booked_by' => 'AKIM SURYANA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '179','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'D1860AGS','status' => '1','booked_by' => 'REDICKY SOLAHUDIN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '180','salespoint_id' => '162','armada_type_id' => '8','plate' => 'BE1082AMC','status' => '1','booked_by' => 'SIGIT DAY SAHRI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '181','salespoint_id' => '162','armada_type_id' => '8','plate' => 'B2505UKK','status' => '1','booked_by' => 'SURNARDI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '182','salespoint_id' => '275','armada_type_id' => '8','plate' => 'D1496AHB','status' => '1','booked_by' => 'RAHMAD MAULANA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '183','salespoint_id' => '19','armada_type_id' => '8','plate' => 'D1762ACQ','status' => '1','booked_by' => 'HANAN IRAWAN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '184','salespoint_id' => '8','armada_type_id' => '8','plate' => 'BE1554AME','status' => '1','booked_by' => 'MUHAMMAD HAYAT','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '185','salespoint_id' => '8','armada_type_id' => '8','plate' => 'D1529AHZ','status' => '1','booked_by' => 'HERU CAKRANINGRAT','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '186','salespoint_id' => '274','armada_type_id' => '8','plate' => 'B2961BIE','status' => '1','booked_by' => 'NUR KOMARUDIN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '187','salespoint_id' => '19','armada_type_id' => '8','plate' => 'BG1954OW','status' => '1','booked_by' => 'SUHANDRI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '188','salespoint_id' => '17','armada_type_id' => '8','plate' => 'D1842AHB','status' => '1','booked_by' => 'SUPRIYADI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '189','salespoint_id' => '274','armada_type_id' => '8','plate' => 'BG1392O','status' => '1','booked_by' => 'Y PURWO CANDRONO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '190','salespoint_id' => '17','armada_type_id' => '8','plate' => 'B2491UKC','status' => '1','booked_by' => 'RUDI SUGIARJO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '191','salespoint_id' => '17','armada_type_id' => '8','plate' => 'BK1563ZX','status' => '1','booked_by' => 'ROSSI RAHMADANI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '192','salespoint_id' => '19','armada_type_id' => '8','plate' => 'BK1191JK','status' => '1','booked_by' => 'JEFRI SAPUTRA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '193','salespoint_id' => '19','armada_type_id' => '8','plate' => 'BK1636AAJ','status' => '1','booked_by' => 'RANDY MOH POHAN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '194','salespoint_id' => '8','armada_type_id' => '8','plate' => 'BK1239IS','status' => '1','booked_by' => 'JEFRI WIJAYA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '195','salespoint_id' => '8','armada_type_id' => '8','plate' => 'BK1432AAQ','status' => '1','booked_by' => 'AGUNG WIRA YUDA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '196','salespoint_id' => '162','armada_type_id' => '8','plate' => 'BK1960FV','status' => '1','booked_by' => 'ERWIN ADINATA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '197','salespoint_id' => '17','armada_type_id' => '8','plate' => 'B1122NOJ','status' => '1','booked_by' => 'EDY YOHANES S.','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '198','salespoint_id' => '162','armada_type_id' => '8','plate' => 'BH1530NI','status' => '1','booked_by' => 'FAHD ALFARISI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '199','salespoint_id' => '171','armada_type_id' => '8','plate' => 'D1778AHB','status' => '1','booked_by' => 'HENDRY SETIAWAN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '200','salespoint_id' => '162','armada_type_id' => '8','plate' => 'BK1230OX','status' => '1','booked_by' => 'AJRAN ADZIM TANJUNG','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '201','salespoint_id' => '162','armada_type_id' => '8','plate' => 'BK1804CC','status' => '1','booked_by' => 'HENDRI ADI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '202','salespoint_id' => '165','armada_type_id' => '8','plate' => 'BA1022QR','status' => '1','booked_by' => 'AZNIL','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '203','salespoint_id' => '8','armada_type_id' => '8','plate' => 'BG1609IE','status' => '1','booked_by' => 'M ERIK RAHSAT','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '204','salespoint_id' => '162','armada_type_id' => '8','plate' => 'BG1558IC','status' => '1','booked_by' => 'FRANSISKUS ALEXSANDER','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '205','salespoint_id' => '162','armada_type_id' => '8','plate' => 'B2330SYJ','status' => '1','booked_by' => 'ARIF WIDIYANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '206','salespoint_id' => '17','armada_type_id' => '8','plate' => 'D1775AHZ','status' => '1','booked_by' => 'IMAM SUBARI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '207','salespoint_id' => '162','armada_type_id' => '8','plate' => 'D1774AHZ','status' => '1','booked_by' => 'AGUS PRAMONO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '208','salespoint_id' => '162','armada_type_id' => '8','plate' => 'BA1927OD','status' => '1','booked_by' => 'RIFKI FARHAN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '209','salespoint_id' => '162','armada_type_id' => '8','plate' => 'BA1056OV','status' => '1','booked_by' => 'KHOIRUL SALEH NASUTION','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '210','salespoint_id' => '162','armada_type_id' => '8','plate' => 'B2016SZP','status' => '1','booked_by' => 'HAN ANGGA KUSUMA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '211','salespoint_id' => '162','armada_type_id' => '8','plate' => 'D1685AHP','status' => '1','booked_by' => 'HARDADI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '212','salespoint_id' => '171','armada_type_id' => '8','plate' => 'D1780AHB','status' => '1','booked_by' => 'RIFKI FATHONI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '213','salespoint_id' => '171','armada_type_id' => '8','plate' => 'B2340UFI','status' => '1','booked_by' => 'MARYANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '214','salespoint_id' => '19','armada_type_id' => '8','plate' => 'BG1956OW','status' => '1','booked_by' => 'DEKI ISNAWAN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '215','salespoint_id' => '162','armada_type_id' => '8','plate' => 'BE1784AAA','status' => '1','booked_by' => 'B. ARI WAHYU WIDIARSO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '216','salespoint_id' => '171','armada_type_id' => '8','plate' => 'B2668SZY','status' => '1','booked_by' => 'YANES WIJAYA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '217','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'B2793BIF','status' => '1','booked_by' => 'YUSUF','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '218','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'D1479AHB','status' => '1','booked_by' => 'BIMBI AFBIANSYAH','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '219','salespoint_id' => '8','armada_type_id' => '8','plate' => 'AD8587VT','status' => '1','booked_by' => 'AGUS TRIANTORO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '220','salespoint_id' => '8','armada_type_id' => '8','plate' => 'AD8595VT','status' => '1','booked_by' => 'MOCHAMMAD NASIR','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '221','salespoint_id' => '162','armada_type_id' => '8','plate' => 'B2164UKK','status' => '1','booked_by' => 'DICKY SETIADIGUNA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '222','salespoint_id' => '162','armada_type_id' => '8','plate' => 'BK1431AAQ','status' => '1','booked_by' => 'EDI SUBINTORO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '223','salespoint_id' => '162','armada_type_id' => '8','plate' => 'D1473AHH','status' => '1','booked_by' => 'DAVIT KURNIAWAN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '224','salespoint_id' => '19','armada_type_id' => '8','plate' => 'D1092AIA','status' => '1','booked_by' => 'M. ROUP','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '225','salespoint_id' => '19','armada_type_id' => '8','plate' => 'D1491AHB','status' => '1','booked_by' => 'LUTFIYADI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '226','salespoint_id' => '19','armada_type_id' => '8','plate' => 'B2329UFI','status' => '1','booked_by' => 'ANDRI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '227','salespoint_id' => '171','armada_type_id' => '8','plate' => 'B9128FCI','status' => '1','booked_by' => 'NAHOR PURBA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '228','salespoint_id' => '19','armada_type_id' => '8','plate' => 'AB1468OX','status' => '1','booked_by' => 'GALIH NUR SUPRIYONO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '229','salespoint_id' => '19','armada_type_id' => '8','plate' => 'AD8590VT','status' => '1','booked_by' => 'ORBIT WIDIARTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '230','salespoint_id' => '19','armada_type_id' => '8','plate' => 'B2174SZZ','status' => '1','booked_by' => 'IPUNG EKA IKSANDRI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '231','salespoint_id' => '140','armada_type_id' => '8','plate' => 'B2273SYN','status' => '1','booked_by' => 'YULIUS RAMZANY MAMAT','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '232','salespoint_id' => '162','armada_type_id' => '8','plate' => 'B2175SZZ','status' => '1','booked_by' => 'JOSEP ANDREANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '233','salespoint_id' => '162','armada_type_id' => '8','plate' => 'B2299SYN','status' => '1','booked_by' => 'WARNOTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '234','salespoint_id' => '162','armada_type_id' => '8','plate' => 'AB1505BQ','status' => '1','booked_by' => 'ANDIS NURCAHYO ENDARWANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '235','salespoint_id' => '17','armada_type_id' => '8','plate' => 'AD8592VT','status' => '1','booked_by' => 'JONI PRIYADI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '236','salespoint_id' => '17','armada_type_id' => '8','plate' => 'B2868BZL','status' => '1','booked_by' => 'ALBASYIR','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '237','salespoint_id' => '162','armada_type_id' => '8','plate' => 'AB1733GY','status' => '1','booked_by' => 'MAHENDRA TORI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '238','salespoint_id' => '162','armada_type_id' => '8','plate' => 'AD8602VT','status' => '1','booked_by' => 'RACHMAN PRASETYA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '239','salespoint_id' => '8','armada_type_id' => '8','plate' => 'AD8581VT','status' => '1','booked_by' => 'ISNAENI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '240','salespoint_id' => '8','armada_type_id' => '8','plate' => 'H8495EQ','status' => '1','booked_by' => 'ARMAN AFDULLAH','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '241','salespoint_id' => '17','armada_type_id' => '8','plate' => 'B2079SYA','status' => '1','booked_by' => 'ZAHROTUS SOFA','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '242','salespoint_id' => NULL,'armada_type_id' => '8','plate' => 'B2010SZZ','status' => '1','booked_by' => 'GESANG SEPTIAN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '243','salespoint_id' => '8','armada_type_id' => '8','plate' => 'B2311SYK','status' => '1','booked_by' => 'RIZA RIZKY APRIAWAN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '244','salespoint_id' => '8','armada_type_id' => '8','plate' => 'B2313SYK','status' => '1','booked_by' => 'SAEPUL RAHMAN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '245','salespoint_id' => '8','armada_type_id' => '8','plate' => 'D1349AFC','status' => '1','booked_by' => 'GUN GUN GUNAWAN','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '246','salespoint_id' => '19','armada_type_id' => '8','plate' => 'B2078SZW','status' => '1','booked_by' => 'DEDI JUNAEDI','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '247','salespoint_id' => '17','armada_type_id' => '8','plate' => 'AD8599VT','status' => '1','booked_by' => 'JEFFRY DJOKO SOESANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '248','salespoint_id' => '162','armada_type_id' => '8','plate' => 'AD8604VT','status' => '1','booked_by' => 'FX INDRA HAPSANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '249','salespoint_id' => '8','armada_type_id' => '8','plate' => 'AD8594VT','status' => '1','booked_by' => 'AGUS HARTANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '250','salespoint_id' => '8','armada_type_id' => '8','plate' => 'H9252HQ','status' => '1','booked_by' => 'AGUS HADIYANTO','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL)
          );
          $armada_types = array(
            array('id' => '1','name' => 'Grand Max Blind Van ','brand_name' => 'Daihatsu','alias' => 'BV','isNiaga' => '1','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '2','name' => 'Grand Max Box','brand_name' => 'Daihatsu','alias' => 'GM Box','isNiaga' => '1','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '3','name' => 'L300','brand_name' => 'Mitsubishi','alias' => 'L300','isNiaga' => '1','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '4','name' => 'FE 71','brand_name' => 'Mitsubishi','alias' => 'Engkle','isNiaga' => '1','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '5','name' => 'FE 71 LC','brand_name' => 'Mitsubishi','alias' => 'Engkle LC','isNiaga' => '1','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '6','name' => 'FE 73','brand_name' => 'Mitsubishi','alias' => 'Double','isNiaga' => '1','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '7','name' => 'FE 74','brand_name' => 'Mitsubishi','alias' => 'Double LC','isNiaga' => '1','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '8','name' => 'GM Mini Bus ','brand_name' => 'Daihatsu','alias' => NULL,'isNiaga' => '0','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '9','name' => 'Xenia ','brand_name' => 'Daihatsu','alias' => NULL,'isNiaga' => '0','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '10','name' => 'Avanza E','brand_name' => 'Toyota','alias' => NULL,'isNiaga' => '0','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '11','name' => 'Avanza G','brand_name' => 'Toyota','alias' => NULL,'isNiaga' => '0','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '12','name' => 'Terios','brand_name' => 'Daihatsu','alias' => NULL,'isNiaga' => '0','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '13','name' => 'Rush','brand_name' => 'Toyota','alias' => NULL,'isNiaga' => '0','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '14','name' => 'Innova','brand_name' => 'Toyota','alias' => NULL,'isNiaga' => '0','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '15','name' => 'Fortuner','brand_name' => 'Toyota','alias' => NULL,'isNiaga' => '0','deleted_at' => NULL,'created_at' => NULL,'updated_at' => NULL)
        );

        foreach($armada_types as $armada_type){
            $newArmadatype              = new ArmadaType;
            $newArmadatype->name        = $armada_type['name'];
            $newArmadatype->brand_name  = $armada_type['brand_name'];
            $newArmadatype->alias       = $armada_type['alias'] ?? null;
            $newArmadatype->isNiaga     = $armada_type['isNiaga'];
            $newArmadatype->save();
        }

        foreach($armadas as $armada){
            $newArmada                  = new Armada;
            $newArmada->salespoint_id   = $armada["salespoint_id"];
            $newArmada->armada_type_id  = $armada["armada_type_id"];
            $newArmada->plate           = $armada["plate"];
            $newArmada->status          = $armada["status"];
            $newArmada->booked_by       = $armada["booked_by"];
            $newArmada->save();
        }
    }
    
}
